"""Bearer Selection (Object 13) resources
"""

# LwM2M Object 13 (Bearer Selection) resource and instance definitions

LWM2M_BEARER_OBJECT = 13

LWM2M_BEARER_INSTANCE = 0

LWM2M_BEARER_RESOURCE_PREFERRED_BEARER = 0
LWM2M_BEARER_RESOURCE_ACCEPT_RSSI_GSM = 1
LWM2M_BEARER_RESOURCE_ACCEPT_RSCP_UMTS = 2
LWM2M_BEARER_RESOURCE_ACCEPT_RSRP_LTE = 3
LWM2M_BEARER_RESOURCE_ACCEPT_RSRP_NBIOT = 10
LWM2M_BEARER_RESOURCE_ACCEPT_RSSI_EVDO = 4
LWM2M_BEARER_RESOURCE_CELL_LOCK_LIST = 5
LWM2M_BEARER_RESOURCE_OPERATOR_LIST = 6
LWM2M_BEARER_RESOURCE_OPERATOR_LIST_MODE = 7
LWM2M_BEARER_RESOURCE_PLMN_LIST = 8
LWM2M_BEARER_RESOURCE_VENDOR_SPECIFIC = 9
LWM2M_BEARER_RESOURCE_HIGH_PRIO_PLMN_TIMER = 11
LWM2M_BEARER_RESOURCE_ATTACH_WITHOUT_PDN = 12

LWM2M_BEARER_AUTO = 0
LWM2M_BEARER_3GPP_PS = 1
LWM2M_BEARER_3GPP_GSM = 2
LWM2M_BEARER_3GPP_UMTS = 3
LWM2M_BEARER_3GPP_LTE = 4
LWM2M_BEARER_EVDO = 5
LWM2M_BEARER_3GPP_CS = 6
LWM2M_BEARER_WLAN = 7
LWM2M_BEARER_ETHERNET = 8
LWM2M_BEARER_DSL = 9
LWM2M_BEARER_BLUETOOTH = 10
LWM2M_BEARER_WIMAX = 11
LWM2M_BEARER_3GPP_CIOT_USER = 12
LWM2M_BEARER_3GPP_CIOT_CONTROL = 13
LWM2M_BEARER_3GPP_NBIOT_CONTROL = 14
LWM2M_BEARER_3GPP_NBIOT_USER = 15
