"""Connection Monitoring (Object 4) resources
"""

# LwM2M Object 4 (Connection Monitoring) resource and instance definitions

LWM2M_CONNMON_OBJECT = 4

LWM2M_CONNMON_INSTANCE = 0

LWM2M_CONNMON_RESOURCE_NET_BEARER = 0
LWM2M_CONNMON_RESOURCE_AVAIL_NET_BEARER = 1
LWM2M_CONNMON_RESOURCE_RSSI = 2
LWM2M_CONNMON_RESOURCE_LINK_QUALITY = 3
LWM2M_CONNMON_RESOURCE_IP_ADDRESSES = 4
LWM2M_CONNMON_RESOURCE_ROUTER_IP_ADDRESSES = 5
LWM2M_CONNMON_RESOURCE_LINK_UTILIZATION = 6
LWM2M_CONNMON_RESOURCE_APN = 7
LWM2M_CONNMON_RESOURCE_CELLID = 8
LWM2M_CONNMON_RESOURCE_SMNC = 9
LWM2M_CONNMON_RESOURCE_SMCC = 10
LWM2M_CONNMON_RESOURCE_SIGNAL_SNR = 11
LWM2M_CONNMON_RESOURCE_LAC = 12
LWM2M_CONNMON_RESOURCE_COVERAGE = 13

LWM2M_CONNMON_BEARER_GSM = 0
LWM2M_CONNMON_BEARER_SCDMA = 1
LWM2M_CONNMON_BEARER_WCDMA = 2
LWM2M_CONNMON_BEARER_CDMA2000 = 3
LWM2M_CONNMON_BEARER_WIMAX = 4
LWM2M_CONNMON_BEARER_LTE_TDD = 5
LWM2M_CONNMON_BEARER_LTE_FDD = 6
LWM2M_CONNMON_BEARER_NB_IOT = 7
LWM2M_CONNMON_BEARER_5G_TDD = 8
LWM2M_CONNMON_BEARER_5G_FDD = 9
LWM2M_CONNMON_BEARER_WLAN = 21
LWM2M_CONNMON_BEARER_BLE = 22
LWM2M_CONNMON_BEARER_802_15_4 = 23
LWM2M_CONNMON_BEARER_ETHERNET = 41
LWM2M_CONNMON_BEARER_DSL = 42
LWM2M_CONNMON_BEARER_PLC = 43
