"""Implementation of Device (Object 3) resources
"""

# LwM2M Object 3 (Device) resource and instance definitions

LWM2M_DEVICE_OBJECT = 3

LWM2M_DEVICE_INSTANCE = 0

LWM2M_DEVICE_RESOURCE_MANUFACTURER = 0
LWM2M_DEVICE_RESOURCE_MODEL = 1
LWM2M_DEVICE_RESOURCE_SERIAL_NUMBER = 2
LWM2M_DEVICE_RESOURCE_FW_VERSION = 3
LWM2M_DEVICE_RESOURCE_REBOOT = 4
LWM2M_DEVICE_RESOURCE_FACTORY_RESET = 5
LWM2M_DEVICE_RESOURCE_AVAILABLE_POWER_SOURCES = 6
LWM2M_DEVICE_RESOURCE_POWER_SOURCE_VOLTAGE = 7
LWM2M_DEVICE_RESOURCE_POWER_SOURCE_CURRENT = 8
LWM2M_DEVICE_RESOURCE_BATTERY_LEVEL = 9
LWM2M_DEVICE_RESOURCE_MEMORY_FREE = 10
LWM2M_DEVICE_RESOURCE_ERROR_CODE = 11
LWM2M_DEVICE_RESOURCE_RESET_ERROR_CODE = 12
LWM2M_DEVICE_RESOURCE_CURRENT_TIME = 13
LWM2M_DEVICE_RESOURCE_UTC_OFFSET = 14
LWM2M_DEVICE_RESOURCE_TIMEZONE = 15
LWM2M_DEVICE_RESOURCE_SUPPORTED_BINDING_MODES = 16
LWM2M_DEVICE_RESOURCE_DEVICE_TYPE = 17
LWM2M_DEVICE_RESOURCE_HARDWARE_VERSION = 18
LWM2M_DEVICE_RESOURCE_SOFTWARE_VERSION = 19
LWM2M_DEVICE_RESOURCE_BATTERY_STATUS = 20
LWM2M_DEVICE_RESOURCE_MEMORY_TOTAL = 21
LWM2M_DEVICE_RESOURCE_EXT_DEVINFO = 22

LWM2M_DEVICE_POWER_DC = 0
LWM2M_DEVICE_POWER_INT_BATTERY = 1
LWM2M_DEVICE_POWER_EXT_BATTERY = 2
LWM2M_DEVICE_POWER_FUEL_CELL = 3
LWM2M_DEVICE_POWER_POE = 4
LWM2M_DEVICE_POWER_USB = 5
LWM2M_DEVICE_POWER_AC = 6
LWM2M_DEVICE_POWER_SOLAR = 7

LWM2M_DEVICE_NO_ERROR = 0
LWM2M_DEVICE_ERR_LOW_BATTERY = 1
LWM2M_DEVICE_ERR_NO_EXT_POWER = 2
LWM2M_DEVICE_ERR_GPS_FAULT = 3
LWM2M_DEVICE_ERR_LOW_RSSI = 4
LWM2M_DEVICE_ERR_OOM = 5
LWM2M_DEVICE_ERR_SMS_FAILURE = 6
LWM2M_DEVICE_ERR_IP_FAILURE = 7
LWM2M_DEVICE_ERR_PERIPH_MALFUNCTION = 8
