"""Software Management (Object 9) resources
"""

from .object import LwM2MObjectInst
from .resource import LwM2MResourceValue

# LwM2M Object 9 (Software Management) resource and instance definitions

LWM2M_SWMGMT_OBJECT = 9

LWM2M_SWMGMT_RESOURCE_PKGNAME = 0
LWM2M_SWMGMT_RESOURCE_PKGVERSION = 1
LWM2M_SWMGMT_RESOURCE_PACKAGE = 2
LWM2M_SWMGMT_RESOURCE_PACKAGE_URI = 3
LWM2M_SWMGMT_RESOURCE_INSTALL = 4
LWM2M_SWMGMT_RESOURCE_CHECKPOINT = 5
LWM2M_SWMGMT_RESOURCE_UNINSTALL = 6
LWM2M_SWMGMT_RESOURCE_UPDATE_STATE = 7
LWM2M_SWMGMT_RESOURCE_UPDATE_SUPPORTED_OBJECT = 8
LWM2M_SWMGMT_RESOURCE_UPDATE_RESULT = 9
LWM2M_SWMGMT_RESOURCE_ACTIVATE = 10
LWM2M_SWMGMT_RESOURCE_DEACTIVATE = 11
LWM2M_SWMGMT_RESOURCE_ACTIVATION_STATE = 12
LWM2M_SWMGMT_RESOURCE_PKG_SETTINGS = 13
LWM2M_SWMGMT_RESOURCE_USERNAME = 14
LWM2M_SWMGMT_RESOURCE_PASSWORD = 15
LWM2M_SWMGMT_RESOURCE_STATUS_REASON = 16
LWM2M_SWMGMT_RESOURCE_SW_COMPONENT_LINK = 17
LWM2M_SWMGMT_RESOURCE_SW_COMPONENT_TREE_LEN = 18

LWM2M_SWMGMT_UPDATE_STATE_INITIAL = 0
LWM2M_SWMGMT_UPDATE_STATE_DOWNLOAD_STARTED = 1
LWM2M_SWMGMT_UPDATE_STATE_DOWNLOADED = 2
LWM2M_SWMGMT_UPDATE_STATE_DELIVERED = 3
LWM2M_SWMGMT_UPDATE_STATE_INSTALLED = 4

LWM2M_SWMGMT_UPDATE_RESULT_INITIAL = 0
LWM2M_SWMGMT_UPDATE_RESULT_DOWNLOADING = 1
LWM2M_SWMGMT_UPDATE_RESULT_INSTALLED = 2
LWM2M_SWMGMT_UPDATE_RESULT_VERIFIED = 3
LWM2M_SWMGMT_UPDATE_RESULT_NO_STORAGE = 50
LWM2M_SWMGMT_UPDATE_RESULT_NO_MEMORY = 51
LWM2M_SWMGMT_UPDATE_RESULT_CONN_FAILED = 52
LWM2M_SWMGMT_UPDATE_RESULT_INTEGRITY_FAILED = 53
LWM2M_SWMGMT_UPDATE_RESULT_UNSUPPORTED = 54
LWM2M_SWMGMT_UPDATE_RESULT_INVALID_URI = 56
LWM2M_SWMGMT_UPDATE_RESULT_DEVICE_ERROR = 57
LWM2M_SWMGMT_UPDATE_RESULT_INSTALL_FAILURE = 58
LWM2M_SWMGMT_UPDATE_RESULT_UNINSTALL_FAILURE = 59

class LwM2MSWManagementObject(LwM2MObjectInst):
    """Base implementation of Object 9 (Software Management) instance

       This object provides the framework for providing a software management and reporting the
       status; it is expected that this class will be extended with device-specific actions.
    """

    def __init__(self, obj_inst):
        super(LwM2MSWManagementObject, self).__init__(LWM2M_SWMGMT_OBJECT, obj_inst)
        # Create default resources for state machine
        self.update_state = LwM2MResourceValue(LWM2M_SWMGMT_OBJECT, self.obj_inst, LWM2M_SWMGMT_RESOURCE_UPDATE_STATE, LWM2M_SWMGMT_UPDATE_STATE_INITIAL)
        self.add_resource(self.update_state)
        self.update_result = LwM2MResourceValue(LWM2M_SWMGMT_OBJECT, self.obj_inst, LWM2M_SWMGMT_RESOURCE_UPDATE_RESULT, LWM2M_SWMGMT_UPDATE_RESULT_INITIAL)
        self.add_resource(self.update_result)

    def report_update_state(self, state):
        self.update_state.set_value(state)

    def report_update_result(self, result):
        self.update_result.set_value(result)
