"""WLAN Connectivity (Object 12) resources
"""

# LwM2M Object 12 (WLAN Connectivity) resource and instance definitions

LWM2M_WLAN_OBJECT = 12

LWM2M_WLAN_BASE_INSTANCE = 0

LWM2M_WLAN_RESOURCE_IFNAME = 0
LWM2M_WLAN_RESOURCE_ENABLE = 1
LWM2M_WLAN_RESOURCE_RADIO_ENABLED = 2
LWM2M_WLAN_RESOURCE_STATUS = 3
LWM2M_WLAN_RESOURCE_BSSID = 4
LWM2M_WLAN_RESOURCE_SSID = 5
LWM2M_WLAN_RESOURCE_BROADCAST_SSID = 6
LWM2M_WLAN_RESOURCE_BEACON_ENABLED = 7
LWM2M_WLAN_RESOURCE_MODE = 8
LWM2M_WLAN_RESOURCE_CHANNEL = 9
LWM2M_WLAN_RESOURCE_AUTO_CHANNEL = 10
LWM2M_WLAN_RESOURCE_SUPPORTED_CHANNELS = 11
LWM2M_WLAN_RESOURCE_CHANNELS_IN_USE = 12
LWM2M_WLAN_RESOURCE_REG_DOMAIN = 13
LWM2M_WLAN_RESOURCE_STANDARD = 14
LWM2M_WLAN_RESOURCE_AUTH_MODE = 15
LWM2M_WLAN_RESOURCE_ENCRYPTION_MODE = 16
LWM2M_WLAN_RESOURCE_WPA_PSK = 17
LWM2M_WLAN_RESOURCE_WPA_KEY_PHRASE = 18
LWM2M_WLAN_RESOURCE_WEP_ENCRYPTION_TYPE = 19
LWM2M_WLAN_RESOURCE_WEP_KEY_INDEX = 20
LWM2M_WLAN_RESOURCE_WEP_KEY_PHRASE = 21
LWM2M_WLAN_RESOURCE_WEP_KEY_1 = 22
LWM2M_WLAN_RESOURCE_WEP_KEY_2 = 23
LWM2M_WLAN_RESOURCE_WEP_KEY_3 = 24
LWM2M_WLAN_RESOURCE_WEP_KEY_4 = 25
LWM2M_WLAN_RESOURCE_RADIUS_SERVER = 26
LWM2M_WLAN_RESOURCE_RADIUS_SERVER_PORT = 27
LWM2M_WLAN_RESOURCE_RADIUS_SECRET = 28
LWM2M_WLAN_RESOURCE_WMM_SUPPORTED = 29
LWM2M_WLAN_RESOURCE_WMM_ENABLED = 30
LWM2M_WLAN_RESOURCE_MAC_CONTROL_ENABLED = 31
LWM2M_WLAN_RESOURCE_MAC_ADDR_LIST = 32
LWM2M_WLAN_RESOURCE_BYTES_SENT = 33
LWM2M_WLAN_RESOURCE_BYTES_RECEIVED = 34
LWM2M_WLAN_RESOURCE_PACKETS_SENT = 35
LWM2M_WLAN_RESOURCE_PACKETS_RECEIVED = 36
LWM2M_WLAN_RESOURCE_TX_ERRORS = 37
LWM2M_WLAN_RESOURCE_RX_ERRORS = 38
LWM2M_WLAN_RESOURCE_UNICAST_PACKETS_SENT = 39
LWM2M_WLAN_RESOURCE_UNICAST_PACKETS_RECEIVED = 40
LWM2M_WLAN_RESOURCE_MULTICAST_PACKETS_SENT = 41
LWM2M_WLAN_RESOURCE_MULTICAST_PACKETS_RECEIVED = 42
LWM2M_WLAN_RESOURCE_BROADCAST_PACKETS_SENT = 43
LWM2M_WLAN_RESOURCE_BROADCAST_PACKETS_RECEIVED = 44
LWM2M_WLAN_RESOURCE_DISCARD_PACKETS_SENT = 45
LWM2M_WLAN_RESOURCE_DISCARD_PACKETS_RECEIVED = 46
LWM2M_WLAN_RESOURCE_UNKNOWN_PACKETS_RECEIVED = 47
LWM2M_WLAN_RESOURCE_VENDOR_SPECIFIC = 48

LWM2M_WLAN_RESOURCE_STATUS_DISABLED = 0
LWM2M_WLAN_RESOURCE_STATUS_UP = 1
LWM2M_WLAN_RESOURCE_STATUS_ERROR = 1

LWM2M_WLAN_RESOURCE_MODE_AP = 0
LWM2M_WLAN_RESOURCE_MODE_CLIENT = 1
LWM2M_WLAN_RESOURCE_MODE_BRIDGE = 2
LWM2M_WLAN_RESOURCE_MODE_REPEATER = 3

LWM2M_WLAN_RESOURCE_STANDARD_80211_A = 0
LWM2M_WLAN_RESOURCE_STANDARD_80211_B = 1
LWM2M_WLAN_RESOURCE_STANDARD_80211_BG = 2
LWM2M_WLAN_RESOURCE_STANDARD_80211_G = 3
LWM2M_WLAN_RESOURCE_STANDARD_80211_N = 4
LWM2M_WLAN_RESOURCE_STANDARD_80211_BGN = 5
LWM2M_WLAN_RESOURCE_STANDARD_80211_AC = 6
LWM2M_WLAN_RESOURCE_STANDARD_80211_AH = 7

LWM2M_WLAN_RESOURCE_AUTH_MODE_OPEN = 0
LWM2M_WLAN_RESOURCE_AUTH_MODE_PSK = 1
LWM2M_WLAN_RESOURCE_AUTH_MODE_EAP = 2
LWM2M_WLAN_RESOURCE_AUTH_MODE_EAP_PSK = 3
LWM2M_WLAN_RESOURCE_AUTH_MODE_EAP_SIM = 4

LWM2M_WLAN_RESOURCE_ENCRYPTION_MODE_AES = 0
LWM2M_WLAN_RESOURCE_ENCRYPTION_MODE_TKIP = 1
LWM2M_WLAN_RESOURCE_ENCRYPTION_MODE_WEP = 2
